import {
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  PlayIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

export const options = {
  chart: {
    height: 350,
    type: "bar",
    zoom: {
      enabled: false,
    },
  },
  plotOptions: {
    bar: {
      borderRadius: 10,
      borderRadiusApplication: "end",
      dataLabels: {
        position: "top",
      },
    },
  },
  xaxis: {
    categories: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    position: "bottom",
    axisBorder: {
      show: false,
    },
    axisTicks: {
      show: false,
    },
    crosshairs: {
      fill: {
        type: "gradient",
        gradient: {
          colorFrom: "#D8E3F0",
          colorTo: "#BED1E6",
          stops: [0, 100],
          opacityFrom: 0.4,
          opacityTo: 0.5,
        },
      },
    },
    tooltip: {
      enabled: true,
    },
  },
  yaxis: {
    axisBorder: {
      show: false,
    },
    axisTicks: {
      show: false,
    },
  },
  title: {
    text: "Monthly Revenue Generated by Client",
    floating: true,
    offsetY: 330,
    align: "center",
    style: {
      color: "#444",
    },
  },
};

export const queryResponseChartOptions = {
  chart: {
    type: "bar",
    zoom: {
      enabled: false,
    },
  },
  plotOptions: {
    bar: {
      borderRadius: 10,
      borderRadiusApplication: "end",
      columnWidth: "70%",
    },
  },
  dataLabels: {
    enabled: false,
  },
  stroke: {
    show: true,
    width: 2,
    colors: ["transparent"],
  },
  fill: {
    opacity: 1,
  },
  tooltip: {
    enabled: true,
  },

  noData: {
    text: "Your charts will appear here once you run a query. Enter your SQL query in the editor above.",
    align: "center",
    verticalAlign: "middle",
    offsetX: 0,
    offsetY: 0,
    style: {
      color: undefined,
      fontSize: "16px",
      fontFamily: undefined,
    },
  },
};

export const editorEvents = [
  {
    name: "Clear",
    icon: XMarkIcon,
    action: (editor) => {
      editor.setValue("");
    },
  },
  {
    name: "Undo",
    icon: ArrowUturnLeftIcon,
    action: (editor) => {
      editor.trigger("source", "undo", null);
    },
  },
  {
    name: "Redo",
    icon: ArrowUturnRightIcon,
    action: (editor) => {
      editor.trigger("source", "redo", null);
    },
  },
  {
    name: "Run Query",
    icon: PlayIcon,
  },
];
